# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2
registries:
  npm-artifactory:
    type: npm-registry
    url: https://artifactory.jfrog.iress.online/artifactory/api/npm/iress-npm/
    token: ${{secrets.IRESS_ARTIFACTORY_ACCESS_TOKEN}}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 1
    registries:
      - npm-artifactory
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
