# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Run unit tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node 
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run tests 
        run: npm run test
